apiVersion: v2
name: parse
description: Parse platform
type: application
version: 0.1.3
appVersion: "1.16.0"
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.x.x
