appId: 'MyParseApp' 
masterkey: 'adminadmin'
#domain: 'rtl.net'
url: 'parse.rtl.net'

postgresql:
  username: postgres
  password: postgres1
  database: postgres
  data_dir: '/ParesDatabase'


dashboard:
  enabled: true
  username: user
  password: user
  url: dashboard.rtl.net
