apiVersion: v1
data:
  app-id: 
   {{ if .Values.appId }}
    {{ .Values.appId | quote }}
   {{ else }}
    {{ "MyParse" }}
   {{ end }} 
  database-url: "postgres://postgres:postgres@postgres/postgres"

kind: ConfigMap
metadata:
  name: parse
  namespace: default