apiVersion: v1
kind: ConfigMap
metadata:
  name: parse
  namespace: default
data:
  app-id: 
   {{ if .Values.appId }}
    {{ .Values.appId | quote }}
   {{ else }}
    {{ "MyParse" }}
   {{ end }} 
  #database-url: "postgres://postgres:@parse-postgresql/postgres"
