apiVersion: v1
data:
  {{ if .Values.appId }}
  app-id: {{ .Values.appId | quote }}
  {{ else }}
  app-id: {{ "MyParse" }}
  {{ end }} 
  database-url: "postgres://postgres:postgres@postgres/postgres"

kind: ConfigMap
metadata:
  name: parse
  namespace: default
