{{- if .Values.url -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parse-ingress
  annotations:
    {{- if .Values.https }} {{ if .Values.certmanager.enabled }}
    {{ "cert-manager.io/cluster-issuer: letsencrypt-prod" }}
    {{- end }} {{ end }}
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: 
     {{ .Values.url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: server
              port:
                number: 1337
  tls:
   - secretName: parse-tls
    
{{- end -}}