apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parse-ingress
  annotations:
    {{ if and .Values.https .Values.certmanager.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{ end }}
    kubernetes.io/ingress.class: "traefik"
     {{ if .Values.https }} 
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure" 
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{ end }}  
spec:
{{ if .Values.url }}
  rules:
  - host: 
     {{ .Values.url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: server
              port:
                number: 1337
{{ end }}  
{{ if .Values.dashboard.enabled }} 
  - host: 
     {{ .Values.dashboard.url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dashboard
              port:
                number: 4040
{{ end }}              
{{ if .Values.https }} 
  tls:
    - secretName: parse-tls
{{ end }}
