{{- if .Values.certmanager.enabled -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.url | quote }}
  namespace: default
spec:
  secretName: {{ .Values.url | quote }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.url | quote }}
  dnsNames:
  - {{ .Values.url | quote }}
 
{{- end -}}
