apiVersion: v1
kind: PersistentVolume
metadata:
  name: parse-pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 
    {{ if .Values.server.postgresdatadir }}
      {{ .Values.server.postgresdatadir | quote }}
    {{ else }}
      {{ "/postgresdata" }}
    {{ end }}
    
    
    
    
    
