apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parse-pvc-hostpath
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi