apiVersion: v1
kind: Secret
metadata:
  name: secret-parse
type: Opaque
stringData:
  master-key: 
    {{ if .Values.masterkey }}
      {{ .Values.masterkey  | quote }}
     {{ else }}
      {{ randAlphaNum 10  | quote }}
    {{ end }}