apiVersion: v1
kind: Secret
metadata:
  name: secret-parse
type: Opaque
data:
  {{ if .Values.server.masterKey }}
  master-key: {{ .Values.server.masterKey | b64enc | quote }}
  {{ else }}
  master-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}