apiVersion: v1
kind: Secret
metadata:
  name: secret-parse
type: Opaque
data:
  master-key: 
    {{ if .Values.masterkey }}
      {{ .Values.masterkey | b64enc | quote }}
     {{ else }}
      {{ randAlphaNum 10 | b64enc | quote }}
    {{ end }}