apiVersion: v1
kind: Service
metadata:
  labels:
    parse.service: server
  name: server
spec:
  ports:
    - name: "1337"
      port: 1337
      targetPort: 1337
  selector:
    parse.service: server
