apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    parse.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
     parse.service: server
  template:
    metadata:
      labels:
        parse.service: server
    spec:
      containers:
        - env:
             - name: PARSE_SERVER_APPLICATION_ID
               valueFrom:
                 configMapKeyRef:
                   name: parse
                   key: app-id
             - name: PARSE_SERVER_MASTER_KEY
               valueFrom:
                 secretKeyRef:
                   name: secret-parse
                   key: master-key
             - name: POSTGRES_PASS
               valueFrom:
                 secretKeyRef:
                   name: secret-postgresql
                   key: postgresql-password
             - name: PARSE_SERVER_DATABASE_URI
               value: postgres://postgres:$(POSTGRES_PASS)@postgresql/postgres
          image: parseplatform/parse-server
          name: server
          ports:
            - containerPort: 1337
      restartPolicy: Always